---
- name: "Creating AWS Infra Using Ansible through Terraform module"
  hosts: localhost
  become: true
  vars_files:
    - variables.yml

  tasks:

    - name: "Installing pip"
      yum:
        name: pip
        state: present
    
    - name: "Installing boto3"
      pip:
        name: boto3
        state: present
        
    - name: "Deployment of Terraform code"
      community.general.terraform:
        project_path: '{{ project_dir }}'
        state: present
        force_init: true

    - name: "Amazon - Fetching Ec2 Info"
      amazon.aws.ec2_instance_info:
        region: "{{ region }}"
        filters:
            "tag:aws:autoscaling:groupName" : "{{ project }}"
      register: ec2

    - name: "Amazon - Creating Dynamic Inventory"
      add_host:
        hostname: '{{ item.public_ip_address }}'
        ansible_host: '{{ item.public_ip_address }}'
        ansible_port: 22
        groups:
          - backends
        ansible_ssh_private_key_file: "./terrakey"
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
      with_items: "{{ ec2.instances }}"


- name: "Deployment From GitHub"
  hosts: backends
  become: true
  serial: 1
  vars_files:
    - variables.yml
  tasks:

    - name: "Package Installation"
      yum:
        name: "{{ packages }}"
        state: present

    - name: "Clonning Github Repository {{ repo }}"
      git:
        repo: "{{ repo }}"
        dest: "/var/website/"
      register: gitstatus 

    - name: "Backend off loading from elb"
      when: gitstatus.changed
      file:
        path: "/var/www/html/health.html"
        mode: 0000

    - name: "Waiting for connection draining"
      when: gitstatus.changed
      wait_for:
        timeout: 30

    - name: "Updating site contents"
      when: gitstatus.changed
      copy:
        src: "/var/website/"
        dest: "/var/www/html/"
        remote_src: true
        owner: apache
        group: apache

    - name: "Loading webserver to elb"
      when: gitstatus.changed
      file:
        path: "/var/www/html/health.html"
        mode: 0644

    - name: "Waiting for connection draining"
      when: gitstatus.changed
      wait_for:
        timeout: 20
